function y = pack_open_tvmc(a, b, c, w, u)

n = size(a,1);
m = size(b,1);
l = size(c,1);

y = [real(a);imag(a);...
     real(b);imag(b);...
     real(c);...
     reshape(real(w),[m*n,1]);reshape(imag(w),[m*n,1]);...
     reshape(real(u),[l*n,1]);reshape(imag(u),[l*n,1])];